"use client";

import { usePathname } from "next/navigation";
import { ToastContainer } from "react-toastify";
import Navbar from "./component/Navbar";

// export const metadata = {
//   title: "Test SOURAV",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const noNavbarRoutes = ["/", "/auth/register","/404"];
  return (
    <html lang="en">
      <head>
        <title>Test SOURAV</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        />
      </head>
      <body>
        {!noNavbarRoutes.includes(pathname) && <Navbar />}
        {children}
        <ToastContainer />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}
